### ISSUE TITLE
`eth_getTransactionReceipt` should invariably return `null` for unexecuted transactions

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#1003]
From @folex:

Sometimes we observe that `eth_getTransactionReceipt` returns a wrapped `Tendermint RPC error` when TX has not yet been mined, or maybe block wasn't completely produced/ingested/synced, I'm not sure.

Judging by the ETH RPC docs, it shouldn't happen
&gt; Unlike eth_getTransactionByHash, which returns null for unknown transactions, and a non-null response with three (3) null fields for a pending transaction, eth_getTransactionReceipt returns null for both pending and unknown transactions.
However, I understand there's some synchronisation between CometBFT and Fendermint is going on in such cases, and requests arriving at "bad" time is something that happens from time to time. Given that, we will try to handle such errors on our side, but since internal error messages are not a Public API, such handlers will break with time. So it would be great to map such errors to `null` or something else sensible, maybe retry?

Error looks like this
```Error: could not coalesce error (error={ "code": 0, "message": "Tendermint RPC error: response error\n\nCaused by:\n    Internal error: could not find results for height #396892 (code: -32603)\n\nLocation:\n    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9" }, payload={ "id": 52, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0xaab9f21c22271f4eceb95c29a5bb8fa2d469c39f45c61220ddd5e94d679a51fc" ] }, code=UNKNOWN_ERROR, version=6.7.1)
    at makeError (file:///Users/aleksei/.local/share/fluence/client/0.16.3-da90e96/node_modules/ethers/lib.esm/utils/errors.js:120:21)
    at JsonRpcProvider.getRpcError (file:///Users/aleksei/.local/share/fluence/client/0.16.3-da90e96/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:649:16)
    at file:///Users/aleksei/.local/share/fluence/client/0.16.3-da90e96/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:264:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: 0,
    message: 'Tendermint RPC error: response error\n' +
      '\n' +
      'Caused by:\n' +
      '    Internal error: could not find results for height #396892 (code: -32603)\n' +
      '\n' +
      'Location:\n' +
      '    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9'
  },
  payload: {
    method: 'eth_getTransactionReceipt',
    params: [
      '0xaab9f21c22271f4eceb95c29a5bb8fa2d469c39f45c61220ddd5e94d679a51fc'
    ],
    id: 52,
    jsonrpc: '2.0'
  }
}```
:pray::skin-tone-2:

[Slack Message](https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1716392258873819?thread_ts=1716392258.873819&cid=C04JR5R1UL8)

**Comment by raulk** [comment]
The contract of `eth_getTransactionReceipt` is to return null if the transaction has not been executed yet (and in chains with deferred execution, inclusion is not enough).

**Comment by raulk** [comment]
Fixed in https://github.com/consensus-shipyard/ipc/pull/1006.
